--- # ----------- CONFIGURABLE START -----------
title: 'Cluas的博客'
description: '侃侃理想、谈谈人生、敲敲代码。'
url: 'https://ysk2014.github.io/blog/' # 域名
signoff: # Your name
share: true
# 分页
paginate: 15
paginate_path: 'page:num'
gems: [jekyll-paginate]
links:
    - name: 首页
      url: /
      external: false
    # - name: 前端
    #   url: /front
    #   external: false
    # - name: CODE
    #   url: /code
    #   external: false
    # - name: 视频
    #   url: /video
    #   external: false
    - name: 归档
      url: /archives
      external: false
    # - name: 标签
    #   url: /tags
    #   external: false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
    - values:
          layout: 'default'

theme: jekyll-theme-slate
